# Generated by Django 6.0.3 on 2026-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
