# Generated by Django 6.0.4 on 2026-05-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_category_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Home', 'Home'), ('Daily', 'Daily'), ('Study', 'Study')], default='Work', max_length=50),
        ),
    ]
