# Generated by Django 6.0.3 on 2026-05-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_reminder_time_remove_task_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Home', 'Home'), ('Study', 'Study'), ('Personal', 'Personal'), ('Daily', 'Daily')], default='Personal', max_length=50),
        ),
    ]
